// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/stats_service (interfaces: statsRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/stats_service/mocks/mock_stats_repo.go -package=mocks ./internal/application/services/stats_service statsRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockstatsRepo is a mock of statsRepo interface.
type MockstatsRepo struct {
	ctrl     *gomock.Controller
	recorder *MockstatsRepoMockRecorder
	isgomock struct{}
}

// MockstatsRepoMockRecorder is the mock recorder for MockstatsRepo.
type MockstatsRepoMockRecorder struct {
	mock *MockstatsRepo
}

// NewMockstatsRepo creates a new mock instance.
func NewMockstatsRepo(ctrl *gomock.Controller) *MockstatsRepo {
	mock := &MockstatsRepo{ctrl: ctrl}
	mock.recorder = &MockstatsRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatsRepo) EXPECT() *MockstatsRepoMockRecorder {
	return m.recorder
}

// GetPRStatistics mocks base method.
func (m *MockstatsRepo) GetPRStatistics(ctx context.Context) (*entities.PRStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatistics", ctx)
	ret0, _ := ret[0].(*entities.PRStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatistics indicates an expected call of GetPRStatistics.
func (mr *MockstatsRepoMockRecorder) GetPRStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatistics", reflect.TypeOf((*MockstatsRepo)(nil).GetPRStatistics), ctx)
}

// GetTeamStatistics mocks base method.
func (m *MockstatsRepo) GetTeamStatistics(ctx context.Context) ([]entities.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStatistics", ctx)
	ret0, _ := ret[0].([]entities.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStatistics indicates an expected call of GetTeamStatistics.
func (mr *MockstatsRepoMockRecorder) GetTeamStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStatistics", reflect.TypeOf((*MockstatsRepo)(nil).GetTeamStatistics), ctx)
}

// GetUserStatistics mocks base method.
func (m *MockstatsRepo) GetUserStatistics(ctx context.Context) ([]entities.UserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatistics", ctx)
	ret0, _ := ret[0].([]entities.UserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatistics indicates an expected call of GetUserStatistics.
func (mr *MockstatsRepoMockRecorder) GetUserStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatistics", reflect.TypeOf((*MockstatsRepo)(nil).GetUserStatistics), ctx)
}
