// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructure/transport/http/handlers (interfaces: userService)
//
// Generated by this command:
//
//	mockgen -destination=internal/infrastructure/transport/http/handlers/mocks/mock_user_service.go -package=mocks ./internal/infrastructure/transport/http/handlers userService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockuserService is a mock of userService interface.
type MockuserService struct {
	ctrl     *gomock.Controller
	recorder *MockuserServiceMockRecorder
	isgomock struct{}
}

// MockuserServiceMockRecorder is the mock recorder for MockuserService.
type MockuserServiceMockRecorder struct {
	mock *MockuserService
}

// NewMockuserService creates a new mock instance.
func NewMockuserService(ctrl *gomock.Controller) *MockuserService {
	mock := &MockuserService{ctrl: ctrl}
	mock.recorder = &MockuserServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserService) EXPECT() *MockuserServiceMockRecorder {
	return m.recorder
}

// DeactivateTeamUsers mocks base method.
func (m *MockuserService) DeactivateTeamUsers(ctx context.Context, teamName string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeactivateTeamUsers", ctx, teamName)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeactivateTeamUsers indicates an expected call of DeactivateTeamUsers.
func (mr *MockuserServiceMockRecorder) DeactivateTeamUsers(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeactivateTeamUsers", reflect.TypeOf((*MockuserService)(nil).DeactivateTeamUsers), ctx, teamName)
}

// GetUserReviews mocks base method.
func (m *MockuserService) GetUserReviews(ctx context.Context, id string) ([]*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserReviews", ctx, id)
	ret0, _ := ret[0].([]*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserReviews indicates an expected call of GetUserReviews.
func (mr *MockuserServiceMockRecorder) GetUserReviews(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserReviews", reflect.TypeOf((*MockuserService)(nil).GetUserReviews), ctx, id)
}

// SetUserActive mocks base method.
func (m *MockuserService) SetUserActive(ctx context.Context, id string, isActive bool) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUserActive", ctx, id, isActive)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// SetUserActive indicates an expected call of SetUserActive.
func (mr *MockuserServiceMockRecorder) SetUserActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUserActive", reflect.TypeOf((*MockuserService)(nil).SetUserActive), ctx, id, isActive)
}
