// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructure/transport/http/handlers (interfaces: teamService)
//
// Generated by this command:
//
//	mockgen -destination=internal/infrastructure/transport/http/handlers/mocks/mock_team_service.go -package=mocks ./internal/infrastructure/transport/http/handlers teamService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockteamService is a mock of teamService interface.
type MockteamService struct {
	ctrl     *gomock.Controller
	recorder *MockteamServiceMockRecorder
	isgomock struct{}
}

// MockteamServiceMockRecorder is the mock recorder for MockteamService.
type MockteamServiceMockRecorder struct {
	mock *MockteamService
}

// NewMockteamService creates a new mock instance.
func NewMockteamService(ctrl *gomock.Controller) *MockteamService {
	mock := &MockteamService{ctrl: ctrl}
	mock.recorder = &MockteamServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamService) EXPECT() *MockteamServiceMockRecorder {
	return m.recorder
}

// CreateTeam mocks base method.
func (m *MockteamService) CreateTeam(ctx context.Context, team *entities.Team) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateTeam", ctx, team)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateTeam indicates an expected call of CreateTeam.
func (mr *MockteamServiceMockRecorder) CreateTeam(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateTeam", reflect.TypeOf((*MockteamService)(nil).CreateTeam), ctx, team)
}

// GetTeam mocks base method.
func (m *MockteamService) GetTeam(ctx context.Context, teamName string) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeam", ctx, teamName)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeam indicates an expected call of GetTeam.
func (mr *MockteamServiceMockRecorder) GetTeam(ctx, teamName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeam", reflect.TypeOf((*MockteamService)(nil).GetTeam), ctx, teamName)
}
