// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructure/transport/http/handlers (interfaces: statsService)
//
// Generated by this command:
//
//	mockgen -destination=internal/infrastructure/transport/http/handlers/mocks/mock_stats_service.go -package=mocks ./internal/infrastructure/transport/http/handlers statsService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockstatsService is a mock of statsService interface.
type MockstatsService struct {
	ctrl     *gomock.Controller
	recorder *MockstatsServiceMockRecorder
	isgomock struct{}
}

// MockstatsServiceMockRecorder is the mock recorder for MockstatsService.
type MockstatsServiceMockRecorder struct {
	mock *MockstatsService
}

// NewMockstatsService creates a new mock instance.
func NewMockstatsService(ctrl *gomock.Controller) *MockstatsService {
	mock := &MockstatsService{ctrl: ctrl}
	mock.recorder = &MockstatsServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockstatsService) EXPECT() *MockstatsServiceMockRecorder {
	return m.recorder
}

// GetPRStatistics mocks base method.
func (m *MockstatsService) GetPRStatistics(ctx context.Context) (*entities.PRStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPRStatistics", ctx)
	ret0, _ := ret[0].(*entities.PRStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPRStatistics indicates an expected call of GetPRStatistics.
func (mr *MockstatsServiceMockRecorder) GetPRStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPRStatistics", reflect.TypeOf((*MockstatsService)(nil).GetPRStatistics), ctx)
}

// GetTeamStatistics mocks base method.
func (m *MockstatsService) GetTeamStatistics(ctx context.Context) ([]entities.TeamStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetTeamStatistics", ctx)
	ret0, _ := ret[0].([]entities.TeamStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetTeamStatistics indicates an expected call of GetTeamStatistics.
func (mr *MockstatsServiceMockRecorder) GetTeamStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetTeamStatistics", reflect.TypeOf((*MockstatsService)(nil).GetTeamStatistics), ctx)
}

// GetUserStatistics mocks base method.
func (m *MockstatsService) GetUserStatistics(ctx context.Context) ([]entities.UserStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetUserStatistics", ctx)
	ret0, _ := ret[0].([]entities.UserStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetUserStatistics indicates an expected call of GetUserStatistics.
func (mr *MockstatsServiceMockRecorder) GetUserStatistics(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetUserStatistics", reflect.TypeOf((*MockstatsService)(nil).GetUserStatistics), ctx)
}
