// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/infrastructure/transport/http/handlers (interfaces: prService)
//
// Generated by this command:
//
//	mockgen -destination=internal/infrastructure/transport/http/handlers/mocks/mock_pr_service.go -package=mocks ./internal/infrastructure/transport/http/handlers prService
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockprService is a mock of prService interface.
type MockprService struct {
	ctrl     *gomock.Controller
	recorder *MockprServiceMockRecorder
	isgomock struct{}
}

// MockprServiceMockRecorder is the mock recorder for MockprService.
type MockprServiceMockRecorder struct {
	mock *MockprService
}

// NewMockprService creates a new mock instance.
func NewMockprService(ctrl *gomock.Controller) *MockprService {
	mock := &MockprService{ctrl: ctrl}
	mock.recorder = &MockprServiceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprService) EXPECT() *MockprServiceMockRecorder {
	return m.recorder
}

// CreatePR mocks base method.
func (m *MockprService) CreatePR(ctx context.Context, prID, prName, authorID string) (*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreatePR", ctx, prID, prName, authorID)
	ret0, _ := ret[0].(*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreatePR indicates an expected call of CreatePR.
func (mr *MockprServiceMockRecorder) CreatePR(ctx, prID, prName, authorID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreatePR", reflect.TypeOf((*MockprService)(nil).CreatePR), ctx, prID, prName, authorID)
}

// GetPR mocks base method.
func (m *MockprService) GetPR(ctx context.Context, prID string) (*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetPR", ctx, prID)
	ret0, _ := ret[0].(*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetPR indicates an expected call of GetPR.
func (mr *MockprServiceMockRecorder) GetPR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetPR", reflect.TypeOf((*MockprService)(nil).GetPR), ctx, prID)
}

// MergePR mocks base method.
func (m *MockprService) MergePR(ctx context.Context, prID string) (*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "MergePR", ctx, prID)
	ret0, _ := ret[0].(*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// MergePR indicates an expected call of MergePR.
func (mr *MockprServiceMockRecorder) MergePR(ctx, prID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "MergePR", reflect.TypeOf((*MockprService)(nil).MergePR), ctx, prID)
}

// ReassignReviewer mocks base method.
func (m *MockprService) ReassignReviewer(ctx context.Context, prID, oldID string) (*entities.PullRequest, string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ReassignReviewer", ctx, prID, oldID)
	ret0, _ := ret[0].(*entities.PullRequest)
	ret1, _ := ret[1].(string)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// ReassignReviewer indicates an expected call of ReassignReviewer.
func (mr *MockprServiceMockRecorder) ReassignReviewer(ctx, prID, oldID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ReassignReviewer", reflect.TypeOf((*MockprService)(nil).ReassignReviewer), ctx, prID, oldID)
}
