// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/pr_service (interfaces: prRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/pr_service/mocks/mock_pr_repo.go -package=mocks ./internal/application/services/pr_service prRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	value_objects "github.com/virogg/pr-assignment-service/internal/domain/value_objects"
	gomock "go.uber.org/mock/gomock"
)

// MockprRepo is a mock of prRepo interface.
type MockprRepo struct {
	ctrl     *gomock.Controller
	recorder *MockprRepoMockRecorder
	isgomock struct{}
}

// MockprRepoMockRecorder is the mock recorder for MockprRepo.
type MockprRepoMockRecorder struct {
	mock *MockprRepo
}

// NewMockprRepo creates a new mock instance.
func NewMockprRepo(ctrl *gomock.Controller) *MockprRepo {
	mock := &MockprRepo{ctrl: ctrl}
	mock.recorder = &MockprRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprRepo) EXPECT() *MockprRepoMockRecorder {
	return m.recorder
}

// AddReviewers mocks base method.
func (m *MockprRepo) AddReviewers(ctx context.Context, id string, reviewerIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewers", ctx, id, reviewerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewers indicates an expected call of AddReviewers.
func (mr *MockprRepoMockRecorder) AddReviewers(ctx, id, reviewerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewers", reflect.TypeOf((*MockprRepo)(nil).AddReviewers), ctx, id, reviewerIDs)
}

// Create mocks base method.
func (m *MockprRepo) Create(ctx context.Context, pr *entities.PullRequest) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, pr)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockprRepoMockRecorder) Create(ctx, pr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockprRepo)(nil).Create), ctx, pr)
}

// GetByID mocks base method.
func (m *MockprRepo) GetByID(ctx context.Context, id string) (*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockprRepoMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockprRepo)(nil).GetByID), ctx, id)
}

// RemoveReviewer mocks base method.
func (m *MockprRepo) RemoveReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReviewer indicates an expected call of RemoveReviewer.
func (mr *MockprRepoMockRecorder) RemoveReviewer(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReviewer", reflect.TypeOf((*MockprRepo)(nil).RemoveReviewer), ctx, prID, reviewerID)
}

// UpdateStatus mocks base method.
func (m *MockprRepo) UpdateStatus(ctx context.Context, id string, status value_objects.PRStatus) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateStatus", ctx, id, status)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateStatus indicates an expected call of UpdateStatus.
func (mr *MockprRepoMockRecorder) UpdateStatus(ctx, id, status any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateStatus", reflect.TypeOf((*MockprRepo)(nil).UpdateStatus), ctx, id, status)
}
