// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/pr_service (interfaces: userGetter)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/pr_service/mocks/mock_user_getter.go -package=mocks ./internal/application/services/pr_service userGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockuserGetter is a mock of userGetter interface.
type MockuserGetter struct {
	ctrl     *gomock.Controller
	recorder *MockuserGetterMockRecorder
	isgomock struct{}
}

// MockuserGetterMockRecorder is the mock recorder for MockuserGetter.
type MockuserGetterMockRecorder struct {
	mock *MockuserGetter
}

// NewMockuserGetter creates a new mock instance.
func NewMockuserGetter(ctrl *gomock.Controller) *MockuserGetter {
	mock := &MockuserGetter{ctrl: ctrl}
	mock.recorder = &MockuserGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserGetter) EXPECT() *MockuserGetterMockRecorder {
	return m.recorder
}

// GetActiveUsersInTeam mocks base method.
func (m *MockuserGetter) GetActiveUsersInTeam(ctx context.Context, id int64, excludeUsers []string) ([]*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersInTeam", ctx, id, excludeUsers)
	ret0, _ := ret[0].([]*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersInTeam indicates an expected call of GetActiveUsersInTeam.
func (mr *MockuserGetterMockRecorder) GetActiveUsersInTeam(ctx, id, excludeUsers any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersInTeam", reflect.TypeOf((*MockuserGetter)(nil).GetActiveUsersInTeam), ctx, id, excludeUsers)
}

// GetByID mocks base method.
func (m *MockuserGetter) GetByID(ctx context.Context, id string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserGetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserGetter)(nil).GetByID), ctx, id)
}
