// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/pr_service (interfaces: teamGetter)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/pr_service/mocks/mock_team_getter.go -package=mocks ./internal/application/services/pr_service teamGetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockteamGetter is a mock of teamGetter interface.
type MockteamGetter struct {
	ctrl     *gomock.Controller
	recorder *MockteamGetterMockRecorder
	isgomock struct{}
}

// MockteamGetterMockRecorder is the mock recorder for MockteamGetter.
type MockteamGetterMockRecorder struct {
	mock *MockteamGetter
}

// NewMockteamGetter creates a new mock instance.
func NewMockteamGetter(ctrl *gomock.Controller) *MockteamGetter {
	mock := &MockteamGetter{ctrl: ctrl}
	mock.recorder = &MockteamGetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamGetter) EXPECT() *MockteamGetterMockRecorder {
	return m.recorder
}

// GetByName mocks base method.
func (m *MockteamGetter) GetByName(ctx context.Context, name string) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByName", ctx, name)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByName indicates an expected call of GetByName.
func (mr *MockteamGetterMockRecorder) GetByName(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByName", reflect.TypeOf((*MockteamGetter)(nil).GetByName), ctx, name)
}
