// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/team_service (interfaces: teamRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/team_service/mocks/mock_team_repo.go -package=mocks ./internal/application/services/team_service teamRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockteamRepo is a mock of teamRepo interface.
type MockteamRepo struct {
	ctrl     *gomock.Controller
	recorder *MockteamRepoMockRecorder
	isgomock struct{}
}

// MockteamRepoMockRecorder is the mock recorder for MockteamRepo.
type MockteamRepoMockRecorder struct {
	mock *MockteamRepo
}

// NewMockteamRepo creates a new mock instance.
func NewMockteamRepo(ctrl *gomock.Controller) *MockteamRepo {
	mock := &MockteamRepo{ctrl: ctrl}
	mock.recorder = &MockteamRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockteamRepo) EXPECT() *MockteamRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockteamRepo) Create(ctx context.Context, team *entities.Team) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, team)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockteamRepoMockRecorder) Create(ctx, team any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockteamRepo)(nil).Create), ctx, team)
}

// GetWithMembers mocks base method.
func (m *MockteamRepo) GetWithMembers(ctx context.Context, name string) (*entities.Team, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetWithMembers", ctx, name)
	ret0, _ := ret[0].(*entities.Team)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetWithMembers indicates an expected call of GetWithMembers.
func (mr *MockteamRepoMockRecorder) GetWithMembers(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetWithMembers", reflect.TypeOf((*MockteamRepo)(nil).GetWithMembers), ctx, name)
}

// TeamExists mocks base method.
func (m *MockteamRepo) TeamExists(ctx context.Context, name string) (bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "TeamExists", ctx, name)
	ret0, _ := ret[0].(bool)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// TeamExists indicates an expected call of TeamExists.
func (mr *MockteamRepoMockRecorder) TeamExists(ctx, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "TeamExists", reflect.TypeOf((*MockteamRepo)(nil).TeamExists), ctx, name)
}
