// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/team_service (interfaces: userCreator)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/team_service/mocks/mock_user_creator.go -package=mocks ./internal/application/services/team_service userCreator
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockuserCreator is a mock of userCreator interface.
type MockuserCreator struct {
	ctrl     *gomock.Controller
	recorder *MockuserCreatorMockRecorder
	isgomock struct{}
}

// MockuserCreatorMockRecorder is the mock recorder for MockuserCreator.
type MockuserCreatorMockRecorder struct {
	mock *MockuserCreator
}

// NewMockuserCreator creates a new mock instance.
func NewMockuserCreator(ctrl *gomock.Controller) *MockuserCreator {
	mock := &MockuserCreator{ctrl: ctrl}
	mock.recorder = &MockuserCreatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserCreator) EXPECT() *MockuserCreatorMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockuserCreator) Create(ctx context.Context, user *entities.User, teamID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, user, teamID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Create indicates an expected call of Create.
func (mr *MockuserCreatorMockRecorder) Create(ctx, user, teamID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockuserCreator)(nil).Create), ctx, user, teamID)
}
