// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/user_service (interfaces: prRepo)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/user_service/mocks/mock_pr_repo.go -package=mocks ./internal/application/services/user_service prRepo
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockprRepo is a mock of prRepo interface.
type MockprRepo struct {
	ctrl     *gomock.Controller
	recorder *MockprRepoMockRecorder
	isgomock struct{}
}

// MockprRepoMockRecorder is the mock recorder for MockprRepo.
type MockprRepoMockRecorder struct {
	mock *MockprRepo
}

// NewMockprRepo creates a new mock instance.
func NewMockprRepo(ctrl *gomock.Controller) *MockprRepo {
	mock := &MockprRepo{ctrl: ctrl}
	mock.recorder = &MockprRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockprRepo) EXPECT() *MockprRepoMockRecorder {
	return m.recorder
}

// AddReviewers mocks base method.
func (m *MockprRepo) AddReviewers(ctx context.Context, id string, reviewerIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AddReviewers", ctx, id, reviewerIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// AddReviewers indicates an expected call of AddReviewers.
func (mr *MockprRepoMockRecorder) AddReviewers(ctx, id, reviewerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AddReviewers", reflect.TypeOf((*MockprRepo)(nil).AddReviewers), ctx, id, reviewerIDs)
}

// GetByReviewer mocks base method.
func (m *MockprRepo) GetByReviewer(ctx context.Context, id string) ([]*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByReviewer", ctx, id)
	ret0, _ := ret[0].([]*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByReviewer indicates an expected call of GetByReviewer.
func (mr *MockprRepoMockRecorder) GetByReviewer(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByReviewer", reflect.TypeOf((*MockprRepo)(nil).GetByReviewer), ctx, id)
}

// GetOpenByReviewers mocks base method.
func (m *MockprRepo) GetOpenByReviewers(ctx context.Context, reviewerIDs []string) ([]*entities.PullRequest, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetOpenByReviewers", ctx, reviewerIDs)
	ret0, _ := ret[0].([]*entities.PullRequest)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetOpenByReviewers indicates an expected call of GetOpenByReviewers.
func (mr *MockprRepoMockRecorder) GetOpenByReviewers(ctx, reviewerIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetOpenByReviewers", reflect.TypeOf((*MockprRepo)(nil).GetOpenByReviewers), ctx, reviewerIDs)
}

// RemoveReviewer mocks base method.
func (m *MockprRepo) RemoveReviewer(ctx context.Context, prID, reviewerID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "RemoveReviewer", ctx, prID, reviewerID)
	ret0, _ := ret[0].(error)
	return ret0
}

// RemoveReviewer indicates an expected call of RemoveReviewer.
func (mr *MockprRepoMockRecorder) RemoveReviewer(ctx, prID, reviewerID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "RemoveReviewer", reflect.TypeOf((*MockprRepo)(nil).RemoveReviewer), ctx, prID, reviewerID)
}
