// Code generated by MockGen. DO NOT EDIT.
// Source: ./internal/application/services/user_service (interfaces: userGetterSetter)
//
// Generated by this command:
//
//	mockgen -destination=internal/application/services/user_service/mocks/mock_user_getter_setter.go -package=mocks ./internal/application/services/user_service userGetterSetter
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entities "github.com/virogg/pr-assignment-service/internal/domain/entities"
	gomock "go.uber.org/mock/gomock"
)

// MockuserGetterSetter is a mock of userGetterSetter interface.
type MockuserGetterSetter struct {
	ctrl     *gomock.Controller
	recorder *MockuserGetterSetterMockRecorder
	isgomock struct{}
}

// MockuserGetterSetterMockRecorder is the mock recorder for MockuserGetterSetter.
type MockuserGetterSetterMockRecorder struct {
	mock *MockuserGetterSetter
}

// NewMockuserGetterSetter creates a new mock instance.
func NewMockuserGetterSetter(ctrl *gomock.Controller) *MockuserGetterSetter {
	mock := &MockuserGetterSetter{ctrl: ctrl}
	mock.recorder = &MockuserGetterSetterMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockuserGetterSetter) EXPECT() *MockuserGetterSetterMockRecorder {
	return m.recorder
}

// GetActiveUsersInTeam mocks base method.
func (m *MockuserGetterSetter) GetActiveUsersInTeam(ctx context.Context, id int64, excludeUserIDs []string) ([]*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetActiveUsersInTeam", ctx, id, excludeUserIDs)
	ret0, _ := ret[0].([]*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetActiveUsersInTeam indicates an expected call of GetActiveUsersInTeam.
func (mr *MockuserGetterSetterMockRecorder) GetActiveUsersInTeam(ctx, id, excludeUserIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetActiveUsersInTeam", reflect.TypeOf((*MockuserGetterSetter)(nil).GetActiveUsersInTeam), ctx, id, excludeUserIDs)
}

// GetByID mocks base method.
func (m *MockuserGetterSetter) GetByID(ctx context.Context, id string) (*entities.User, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetByID", ctx, id)
	ret0, _ := ret[0].(*entities.User)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetByID indicates an expected call of GetByID.
func (mr *MockuserGetterSetterMockRecorder) GetByID(ctx, id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetByID", reflect.TypeOf((*MockuserGetterSetter)(nil).GetByID), ctx, id)
}

// SetActive mocks base method.
func (m *MockuserGetterSetter) SetActive(ctx context.Context, id string, isActive bool) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetActive", ctx, id, isActive)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetActive indicates an expected call of SetActive.
func (mr *MockuserGetterSetterMockRecorder) SetActive(ctx, id, isActive any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetActive", reflect.TypeOf((*MockuserGetterSetter)(nil).SetActive), ctx, id, isActive)
}

// SetUsersInactive mocks base method.
func (m *MockuserGetterSetter) SetUsersInactive(ctx context.Context, userIDs []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetUsersInactive", ctx, userIDs)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetUsersInactive indicates an expected call of SetUsersInactive.
func (mr *MockuserGetterSetterMockRecorder) SetUsersInactive(ctx, userIDs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetUsersInactive", reflect.TypeOf((*MockuserGetterSetter)(nil).SetUsersInactive), ctx, userIDs)
}
